### ISSUE TITLE
AMR

### ISSUE THREAD

**Issue by Qyinqi** [mzl13/Lithium#1]
Hi mu, I found that the grid thinning function was not implemented when I reproduced the program you provided. Is this a problem with the algorithm framework or the function of refining the grid is not written in Lithium.cpp?

**Comment by mzl13** [comment]
The AMR is not implemented, only one layer grids are used in the project.

**Comment by mzl13** [comment]
you could contact me by mzl13.cn#gmail.com ( replace # by @)
